name: Garmin Connect to Todoist Task

on:
  schedule:
    - cron: "*/10 * * * *" # Run workflow very 10 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  garmin-connect-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore the task tracker cache
        uses: actions/cache@v4
        with:
          path: created_tasks.db
          key: garmin-tasks-db

      - name: Run the Garmin Connect script
        env:
          GARMIN_USER: ${{ secrets.GARMIN_USER }}
          GARMIN_PASS: ${{ secrets.GARMIN_PASS }}
          TODOIST_SECTION_ID: ${{ secrets.TODOIST_SECTION_ID }}
          TODOIST_PROJECT_ID: ${{ secrets.TODOIST_PROJECT_ID }}
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
        run: |
          python garmin_connect.py
